In [3]:
import numpy as np

In [4]:
# Exercice 1

# Q1
arr1 = np.arange(10)
print(arr1)

# Q2
arr2 = np.full((3, 3), True, dtype=bool)
print(arr2)

# Q3
arr3 = np.random.rand(10)
arr3

[0 1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


array([0.1235823 , 0.9363792 , 0.76362838, 0.11520062, 0.60076131,
       0.30821421, 0.63220397, 0.32862372, 0.45931064, 0.8440014 ])

In [8]:
# Exercice 2

# Q1
arr1[arr1 % 2 == 0] = -1
print(arr1)

# Q2
print(arr2[1, 2]) # [1][2]

# Q3
arr3 = np.random.rand(4, 4)
print(arr3)
print()
print(arr3[:, :-1])
print()
print(np.sum(arr3[:, :-1], axis=1))
print()
arr3[:, -1] = np.sum(arr3[:, :-1], axis=1)
print(arr3)

[-1  1 -1  3 -1  5 -1  7 -1  9]
True
[[0.73358838 0.37534416 0.12698785 0.71958673]
 [0.43234844 0.34110501 0.53480566 0.70345477]
 [0.67754605 0.07614108 0.95817382 0.77198169]
 [0.62718529 0.11560649 0.43453157 0.40077733]]

[[0.73358838 0.37534416 0.12698785]
 [0.43234844 0.34110501 0.53480566]
 [0.67754605 0.07614108 0.95817382]
 [0.62718529 0.11560649 0.43453157]]

[1.23592039 1.30825911 1.71186096 1.17732334]

[[0.73358838 0.37534416 0.12698785 1.23592039]
 [0.43234844 0.34110501 0.53480566 1.30825911]
 [0.67754605 0.07614108 0.95817382 1.71186096]
 [0.62718529 0.11560649 0.43453157 1.17732334]]
