# Travaux Dirigés sur Numpy Correction

## Partie 1

### Exercice 1 : Création et Manipulation de Tableaux Numpy

1. Créez un tableau numpy à une dimension contenant les nombres de 0 à 9.

2. Créez un tableau numpy à deux dimensions (3x3) rempli de valeurs booléennes True.

3. Créez un tableau numpy à une dimension de taille 10, rempli de nombres aléatoires entre 0 et 1.

### Solution 1 :

In [1]:
# Exercice 1
import numpy as np

# Question 1
arr1 = np.arange(10)
print(arr1)

# Question 2
arr2 = np.full((3, 3), True, dtype=bool)
print(arr2)

# Question 3
arr3 = np.random.rand(10)
arr3

[0 1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


array([0.6195507 , 0.05004987, 0.99955282, 0.88608984, 0.23305772,
       0.34378416, 0.42259976, 0.75302104, 0.22401783, 0.86192472])

### Exercice 2 : Accès et Modification d'Éléments

1. À l'aide du tableau créé dans la question 1 de l'exercice précédent, remplacez tous les éléments pairs par -1.

2. Accédez à l'élément situé à la deuxième ligne et troisième colonne du tableau créé dans la question 2 de l'exercice précédent.

3. Créez un tableau numpy à deux dimensions (4x4) et remplacez la dernière colonne par la somme des trois premières colonnes.

### Solution 2 :

In [18]:
# Exercice 2
# Utilisez les résultats de l'exercice précédent

# Question 1
arr1[arr1 % 2 == 0] = -1
print(arr1)

# Question 2
element = arr2[1, 2]
print(element)

# Question 3
arr3 = np.random.rand(4, 4)
print(arr3)
print()
print(arr3[:, :-1])
print()
print(np.sum(arr3[:, :-1], axis=1))
print()
arr3[:, -1] = np.sum(arr3[:, :-1], axis=1)
print(arr3)

[-1  1 -1  3 -1  5 -1  7 -1  9]
True
[[0.77488119 0.05609281 0.72384682 0.22057142]
 [0.71744609 0.37817593 0.53086058 0.68520117]
 [0.58441469 0.87235098 0.31123198 0.12033376]
 [0.67485898 0.65508982 0.17303011 0.94826327]]

[[0.77488119 0.05609281 0.72384682]
 [0.71744609 0.37817593 0.53086058]
 [0.58441469 0.87235098 0.31123198]
 [0.67485898 0.65508982 0.17303011]]

[1.55482082 1.6264826  1.76799766 1.5029789 ]

[[0.77488119 0.05609281 0.72384682 1.55482082]
 [0.71744609 0.37817593 0.53086058 1.6264826 ]
 [0.58441469 0.87235098 0.31123198 1.76799766]
 [0.67485898 0.65508982 0.17303011 1.5029789 ]]


### Exercice 3 : Opérations Avancées

1. Créez deux tableaux numpy de taille 5 avec des valeurs aléatoires, puis effectuez leur produit matriciel.

2. Créez une fonction qui prend un tableau numpy en entrée et renvoie le tableau résultant de l'application de la fonction sinus à chaque élément.

3. Créez un tableau numpy à deux dimensions (5x5) avec des valeurs aléatoires, puis normalisez-le de manière à ce que la somme de chaque ligne soit égale à 1.

### Solution 3 :

In [20]:
# Exercice 3
# Utilisez les résultats des exercices précédents

# Question 1
matrix1 = np.random.rand(5, 5)
matrix2 = np.random.rand(5, 5)
product_matrix = np.dot(matrix1, matrix2)
print(product_matrix)

# Question 2
def apply_sin(arr):
    return np.sin(arr)

# Question 3
random_matrix = np.random.rand(5, 5)
normalized_matrix = random_matrix / random_matrix.sum(axis=1, keepdims=True)
print()
print(normalized_matrix)

[[1.11202292 1.6097204  2.15618333 1.06129756 1.72116363]
 [1.69785513 1.53749518 2.5232975  1.32044486 2.24535483]
 [0.94758818 0.89286144 1.88745951 0.54103703 1.65320347]
 [1.27374093 1.05578387 1.39457602 0.87237844 1.38787201]
 [1.02621623 1.29290529 2.14924998 0.92307223 1.72911301]]

[[0.11998267 0.00729971 0.27424427 0.28293551 0.31553784]
 [0.37085364 0.04625968 0.36233043 0.21418274 0.00637352]
 [0.1139248  0.29021545 0.24717723 0.15788399 0.19079852]
 [0.16382707 0.11650902 0.06757376 0.12857629 0.52351386]
 [0.12241096 0.20652068 0.03006983 0.31944883 0.3215497 ]]


## Partie 2

### Exercice 1 : Création de Tableaux Numpy

1. Créez un tableau numpy à une dimension avec les nombres de 1 à 10.

2. Créez un tableau numpy à deux dimensions (3x4) avec des nombres aléatoires entre 0 et 1.

### Solution 1 :

In [24]:
# Question 1
arr1 = np.arange(1, 11)
print(arr1)
print()
# Question 2
arr2 = np.random.rand(3, 4)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]

[[0.00964684 0.5634973  0.08196417 0.512088  ]
 [0.83094329 0.46319326 0.9946436  0.21591894]
 [0.24157615 0.28527461 0.75279231 0.48435411]]


### Exercice 2 : Manipulation de Tableaux Numpy

1. Inversez l'ordre des éléments dans le tableau créé dans la question 1 de l'exercice précédent.

2. Trouvez la moyenne du tableau créé dans la question 2 de l'exercice précédent.

### Solution 2 :

In [25]:
# Utilisez les résultats de l'exercice précédent

# Question 1
arr1_reverse = np.flip(arr1)
print(arr1_reverse)
# Question 2
mean_arr2 = np.mean(arr2)
print(mean_arr2)

[10  9  8  7  6  5  4  3  2  1]
0.452991047718581


### Exercice 3 : Opérations Avancées

1. Créez une fonction qui prend deux tableaux numpy en entrée et renvoie leur concaténation horizontale.

2. Créez un tableau numpy à deux dimensions (4x5) avec des valeurs aléatoires, puis remplacez toutes les valeurs inférieures à la moyenne par 0.

### Solution 3 :

In [29]:
# Utilisez les résultats des exercices précédents

# Question 1
def horizontal_concat(arr1, arr2):
    return np.hstack((arr1, arr2))

print(horizontal_concat(np.zeros((2,3)), np.ones((2,1))))
# Question 2
random_matrix = np.random.rand(4, 5)
print()
print(random_matrix)

mean_value = np.mean(random_matrix)
random_matrix[random_matrix < mean_value] = 0


print()
print(random_matrix)

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]]

[[0.66850037 0.1895272  0.34258349 0.03851585 0.53065659]
 [0.87318684 0.73553374 0.75063405 0.61792055 0.42833607]
 [0.42524372 0.11446207 0.9562565  0.66670504 0.42556742]
 [0.91293416 0.28827756 0.58475232 0.75429617 0.50968061]]

[[0.66850037 0.         0.         0.         0.        ]
 [0.87318684 0.73553374 0.75063405 0.61792055 0.        ]
 [0.         0.         0.9562565  0.66670504 0.        ]
 [0.91293416 0.         0.58475232 0.75429617 0.        ]]


### Exercice 4 : Manipulation de Tableaux 3D

1. Créez un tableau numpy à trois dimensions (2x3x4) avec des nombres entiers aléatoires entre 1 et 100.

2. Trouvez la somme des éléments le long de l'axe des colonnes pour le tableau créé dans la question 1.

### Solution 4 :

In [33]:
# Question 1
arr_3d = np.random.randint(1, 101, (2, 3, 4))
print()
print(arr_3d)

# Question 2
sum_along_columns = np.sum(arr_3d, axis=1)
print()
print(sum_along_columns)


[[[23 37 49 11]
  [17 58 95 49]
  [88 74 51 46]]

 [[70 96 78 53]
  [58 84 63 74]
  [26 57 98 63]]]

[[128 169 195 106]
 [154 237 239 190]]


### Exercice 5 : Broadcasting

1. Créez un tableau numpy à deux dimensions (5x3) avec des nombres aléatoires entre 1 et 10.

2. Ajoutez un tableau numpy à une dimension (1x3) à chaque ligne du tableau créé dans la question 1.

### Solution 5 :

In [36]:
# Question 1
arr_broadcasting = np.random.randint(1, 11, (5, 3))
print(arr_broadcasting)

# Question 2
arr_to_add = np.array([1, 2, 3])
result_broadcasting = arr_broadcasting + arr_to_add
print()
print(result_broadcasting)

[[ 8  6  7]
 [ 3 10  3]
 [ 1  5  9]
 [ 8  3  5]
 [ 6  1  9]]

[[ 9  8 10]
 [ 4 12  6]
 [ 2  7 12]
 [ 9  5  8]
 [ 7  3 12]]


### Exercice 6 : Opérations Matricielles

1. Créez deux matrices numpy de taille 3x3 avec des valeurs aléatoires.

2. Calculez l'inverse de la première matrice créée dans la question 1.

### Solution 6 :

In [35]:
# Question 1
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)
print(matrix1)
# Question 2
inverse_matrix1 = np.linalg.inv(matrix1)
print()
print(matrix1)

[[0.47540124 0.92885537 0.74886658]
 [0.57747893 0.48637069 0.63872623]
 [0.10642694 0.05381592 0.98676014]]

[[0.47540124 0.92885537 0.74886658]
 [0.57747893 0.48637069 0.63872623]
 [0.10642694 0.05381592 0.98676014]]


### Exercice 7 : Opérations Avancées

1. Créez une fonction qui prend un tableau numpy à deux dimensions en entrée et renvoie un nouveau tableau où chaque élément est élevé à la puissance de son indice de colonne.

2. Créez un tableau numpy à deux dimensions (5x5) avec des nombres aléatoires, puis remplacez chaque élément par la valeur maximale de sa ligne.

### Solution 7 :

In [52]:
# Question 1
def power_by_column_index(arr):
    return arr ** np.arange(arr.shape[1])

arr = np.array([[1,4, 5], [3, 2, 6]])
print(power_by_column_index(arr))

# Question 2
random_matrix_advanced = np.random.rand(5, 5)
print()
print(random_matrix_advanced)
max_values_per_row = np.max(random_matrix_advanced, axis=1, keepdims=True)
print()
print(max_values_per_row)
for i in range(random_matrix_advanced.shape[0]):
    random_matrix_advanced[i, :] = max_values_per_row[i, 0]
print()
print(random_matrix_advanced)

[[ 1  4 25]
 [ 1  2 36]]

[[0.33274452 0.90512442 0.34203256 0.62950872 0.9039496 ]
 [0.0050944  0.64923003 0.58043603 0.20444003 0.3412074 ]
 [0.6563893  0.76897372 0.60202701 0.57585264 0.46232758]
 [0.9827572  0.87438235 0.69921137 0.65162671 0.74430068]
 [0.32628966 0.66099397 0.35207268 0.67928013 0.84810414]]

[[0.90512442]
 [0.64923003]
 [0.76897372]
 [0.9827572 ]
 [0.84810414]]

[[0.90512442 0.90512442 0.90512442 0.90512442 0.90512442]
 [0.64923003 0.64923003 0.64923003 0.64923003 0.64923003]
 [0.76897372 0.76897372 0.76897372 0.76897372 0.76897372]
 [0.9827572  0.9827572  0.9827572  0.9827572  0.9827572 ]
 [0.84810414 0.84810414 0.84810414 0.84810414 0.84810414]]


### Exercice 8 : Manipulation de Chaînes de Caractères avec Numpy

1. Créez un tableau numpy à une dimension contenant cinq noms différents sous forme de chaînes de caractères.

2. Ajoutez le préfixe "M." à chaque nom dans le tableau créé dans la question 1.

### Solution 8 :

In [53]:
# Question 1
names_array = np.array(["Alice", "Bob", "Charlie", "David", "Eve"])

# Question 2
names_with_prefix = np.core.defchararray.add("M. ", names_array)
print(names_with_prefix)

['M. Alice' 'M. Bob' 'M. Charlie' 'M. David' 'M. Eve']


### Exercice 9 : Opérations Logiques avec Numpy

1. Créez un tableau numpy à une dimension contenant des valeurs aléatoires entières entre 0 et 10.

2. Remplacez toutes les valeurs supérieures à 5 par 1 et toutes les autres valeurs par 0.

### Solution 9 :

In [54]:
# Question 1
random_integers = np.random.randint(0, 11, 10)
print(random_integers)

# Question 2
binary_array = np.where(random_integers > 5, 1, 0)
print()
print(binary_array)

[7 7 8 5 5 6 7 8 0 3]

[1 1 1 0 0 1 1 1 0 0]


### Exercice 10 : Manipulation Avancée avec Numpy

1. Créez un tableau numpy à deux dimensions (4x6) avec des nombres entiers aléatoires entre -10 et 10.

2. Remplacez toutes les valeurs négatives par zéro, multipliez toutes les valeurs positives par 2, et transposez finalement la matrice.

### Solution 10 :

In [56]:
# Question 1
random_int_matrix = np.random.randint(-10, 11, (4, 6))
print(random_int_matrix)

# Question 2
processed_matrix = np.where(random_int_matrix < 0, 0, random_int_matrix * 2)
print()
print(processed_matrix)
transposed_matrix = processed_matrix.T
print()
print(transposed_matrix)

[[-6  5 -8  5 -2  3]
 [-3 -8  1 -4  8 -6]
 [-4 -4  4 -6 -3  3]
 [ 8 -7  5 -7 -6 -3]]

[[ 0 10  0 10  0  6]
 [ 0  0  2  0 16  0]
 [ 0  0  8  0  0  6]
 [16  0 10  0  0  0]]

[[ 0  0  0 16]
 [10  0  0  0]
 [ 0  2  8 10]
 [10  0  0  0]
 [ 0 16  0  0]
 [ 6  0  6  0]]


### Exercice 11 : Calcul de la Moyenne et de l'Écart-Type

1. Créez un tableau numpy à une dimension contenant 10 valeurs aléatoires.

2. Calculez la moyenne et l'écart-type du tableau.

### Solution 11 :

In [58]:
# Question 1
random_values = np.random.randn(10)

# Question 2
mean_value = np.mean(random_values)
print(mean_value)
std_deviation = np.std(random_values)
print(std_deviation)

-0.06090642605297545
0.839057034593385


### Exercice 12 : Opérations sur les Indicateurs Booléens

1. Créez un tableau numpy à une dimension avec des valeurs entières aléatoires entre 0 et 9.

2. Identifiez et comptez le nombre d'éléments pairs dans le tableau.

### Solution 12 :

In [60]:
# Question 1
random_integers = np.random.randint(0, 10, 10)
print(random_integers)

# Question 2
even_count = np.sum(random_integers % 2 == 0)
print()
print(even_count)

[5 9 6 4 4 3 2 9 7 6]

5


### Exercice 13 : Manipulation de Tableaux 3D

1. Créez un tableau numpy à trois dimensions (3x4x5) avec des valeurs aléatoires.

2. Calculez la somme des valeurs le long de chaque dimension.

### Solution 13 :

In [62]:
# Question 1
random_3d_array = np.random.randn(3, 4, 5)
print(random_3d_array)

# Question 2
sum_along_axes = np.sum(random_3d_array, axis=(0, 1, 2))
print()
print(sum_along_axes)
print(np.sum(random_3d_array))

[[[-0.71926495  0.50735249  1.71045502  0.87377169 -0.7752877 ]
  [-0.02740361 -0.16868233  0.62967457  0.07235857 -0.18860246]
  [ 1.6136198   0.06388794 -0.43442617  0.49800674 -0.09277891]
  [ 0.06077013 -0.51530334  1.05147599 -0.06486952  1.09216126]]

 [[-0.63870115  1.11416398  0.86912529 -0.59102953  0.36856317]
  [-0.41043158  0.3020394   1.94251709 -1.34364824  0.37651562]
  [-0.21899962  0.17136468  0.13174876  0.43264464 -0.81948117]
  [-0.91806483  0.16625548 -1.86094673 -0.30460057 -0.87583529]]

 [[ 2.18037599  2.20024431  0.690864   -1.87053972  0.54119551]
  [-0.99143881  4.65298258  0.5789475  -0.93702385 -0.04096232]
  [-0.07851068  0.38437603 -0.75310735  0.07621851 -1.54929973]
  [ 0.28047859 -0.54579463  0.15613512  0.01027923 -0.04895757]]]

8.016577328416322
8.016577328416322


### Exercice 14 : Opérations avec des Indices

1. Créez un tableau numpy à une dimension contenant 20 éléments de 0 à 19.

2. Obtenez les indices des éléments qui sont des carrés parfaits (ex. 0, 1, 4, 9, ...).

### Solution 14 :

In [3]:
# Question 1
linear_array = np.arange(20)
print(linear_array)

# Question 2
perfect_square_indices = np.where(np.sqrt(linear_array) % 1 == 0)[0]
print()
print(perfect_square_indices)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[ 0  1  4  9 16]


### Exercice 15 : Opérations de Transformation

1. Créez un tableau numpy à deux dimensions (5x6) avec des valeurs aléatoires entières entre -50 et 50.

2. Soustrayez la moyenne de chaque colonne du tableau.

### Solution 15 :

In [65]:
# Question 1
random_int_matrix = np.random.randint(-50, 51, (5, 6))
print(random_int_matrix)

# Question 2
mean_per_column = np.mean(random_int_matrix, axis=0)
transformed_matrix = random_int_matrix - mean_per_column
print()
print(transformed_matrix)

[[ 36  32 -36  -8  -8 -41]
 [  6 -15 -43 -25  27   5]
 [-16 -27  19  -8 -34 -15]
 [  9   0  43   6  29  49]
 [ 33 -42  45  24  -4 -50]]

[[ 22.4  42.4 -41.6  -5.8 -10.  -30.6]
 [ -7.6  -4.6 -48.6 -22.8  25.   15.4]
 [-29.6 -16.6  13.4  -5.8 -36.   -4.6]
 [ -4.6  10.4  37.4   8.2  27.   59.4]
 [ 19.4 -31.6  39.4  26.2  -6.  -39.6]]
