# 2D Numpy en Python


## Objectifs

* Opérer confortablement avec `numpy`
* Effectuer des opérations complexes avec `numpy`


<h2>Table des matières</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li><a href="#Créer-un-tableau-Numpy-2D">Créer un tableau Numpy 2D</a></li>
        <li><a href="#Accéder-à-différents-éléments-d'un-tableau-Numpy">Accéder à différents éléments d'un tableau Numpy</a></li>
        <li><a href="#Opérations-de-base">Opérations de base</a></li>
    </ul>
  
</div>

<hr>


## Créer un tableau Numpy 2D


In [1]:
import numpy as np

Considérez la liste `a`, qui contient trois listes imbriquées **chacune de taille égale**.


In [2]:
# Create une liste

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

On peut convertir la liste en un tableau Numpy comme suit:


In [3]:
# Convertir une liste en tableau Numpy
# Chaque élément est du même type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Nous pouvons utiliser l'attribut `ndim` pour obtenir le nombre d'axes ou de dimensions, appelé rang.


In [4]:
# Afficher la dimension

A.ndim

2

L'attribut `shape` renvoie un tuple correspondant à la taille ou au nombre de chaque dimension.


In [5]:

A.shape

(3, 3)

Le nombre total d'éléments dans le tableau est donné par l'attribut `size`.


In [6]:

A.size

9

<hr>


## Accéder à différents éléments d'un tableau Numpy


Nous pouvons utiliser des crochets rectangulaires pour accéder aux différents éléments du tableau. La correspondance entre les crochets rectangulaires et la liste ainsi que la représentation rectangulaire sont illustrées dans la figure suivante pour un tableau de dimensions 3x3 :


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoEg.png" width="500">


Nous pouvons accéder à la deuxième ligne, troisième colonne comme indiqué dans la figure suivante :


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="400">


Nous utilisons simplement les crochets carrés et les indices correspondant à l'élément que nous voulons :


In [7]:
A[1, 2]

23

Nous pouvons également utiliser la notation suivante pour obtenir les éléments :

In [8]:

A[1][2]

23

Considérez les éléments montrés dans la figure suivante


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFF.png" width="400">


Nous pouvons accéder à l'élément de la manière suivante :


In [9]:

A[0][0]

11

Nous pouvons également utiliser le découpage (slicing) dans les tableaux numpy. Considérons la figure suivante. Nous aimerions obtenir les deux premières colonnes de la première ligne.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFSF.png" width="400">


Cela peut être fait avec la syntaxe suivante :


In [10]:

A[0][0:2]

array([11, 12])

De même, nous pouvons obtenir les deux premières lignes de la troisième colonne de la manière suivante :


In [11]:

A[0:2, 2]

array([13, 23])

Correspondant à la figure suivante :

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/2D_numpy.png" width="400"><br />


## Operations de base


Nous pouvons également additionner des tableaux. Le processus est identique à l'addition de matrices. L'addition matricielle de `X` et `Y` est illustrée dans la figure suivante :


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoAdd.png" width="500">


Créons deux tableaux  <code>X</code> et <code>Y</code>


In [12]:
X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [13]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

On peut les additionner comme suit.


In [14]:
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

Multiplier un tableau numpy par un scalaire est identique à multiplier une matrice par un scalaire. Si nous multiplions la matrice `Y` par le scalaire 2, nous multiplions simplement chaque élément de la matrice par 2, comme indiqué dans la figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoDb.png" width="500">


Nous pouvons effectuer la même opération en numpy comme suit


In [15]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [16]:
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

La multiplication de deux tableaux correspond à un produit élément par élément ou produit de Hadamard. Considérez la matrice `X` et `Y`. Le produit de Hadamard correspond à multiplier chaque élément à la même position, c'est-à-dire multiplier les éléments contenus dans les mêmes cases de couleur ensemble. Le résultat est une nouvelle matrice de la même taille que la matrice `Y` ou `X`, comme indiqué dans la figure suivante.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoMul.png" width="500">


Nous pouvons effectuer un produit élément par élément des tableaux `X` et `Y` comme suit :


In [17]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [18]:
X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [19]:
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

Nous pouvons également effectuer une multiplication matricielle avec les tableaux numpy `A` et `B` comme suit :


D'abord, on définit matrice <code>A</code> et <code>B</code>:


In [20]:
A = np.array([[0, 1, 1], [1, 0, 1]])
print(A.shape)
A

(2, 3)


array([[0, 1, 1],
       [1, 0, 1]])

In [21]:
B = np.array([[1, 1], [1, 1], [-1, 1]])
print(B.shape)
B

(3, 2)


array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

Nous utilisons la fonction numpy `dot` pour multiplier les tableaux ensemble.


In [22]:
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [23]:
# le sinus de Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

Nous utilisons l'attribut numpy `T` pour calculer la matrice transposée


In [24]:
# Crée une matrice C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [25]:
# Obtenir la transposée de C

C.T

array([[1, 2, 3],
       [1, 2, 3]])